apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-deploy
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
