apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: db-service
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db-deploy
  type: ClusterIP
status:
  loadBalancer: {}
